version: "3"
networks:
  hyperledger-ov:
    external:
      name: hyperledger-ov
services:
  ca0:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: ca0.example.com
    image: hyperledger/fabric-ca:latest
    networks:
      hyperledger-ov:
        aliases:
        - ca_peerOrg1
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-org1
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
    - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/c47be7d4f08cc35f7a85af06bc1df69eb9cb237e7cd6898cc0bed94ba7315043_sk
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org1.example.com-cert.pem
      --ca.keyfile /etc/hyperledger/fabric-ca-server-config/c47be7d4f08cc35f7a85af06bc1df69eb9cb237e7cd6898cc0bed94ba7315043_sk -b admin:adminpw
      -d'
    volumes:
    - ./crypto-config/peerOrganizations/org1.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
  ca1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: ca1.example.com
    image: hyperledger/fabric-ca:latest
    networks:
      hyperledger-ov:
        aliases:
        - ca_peerOrg2
    environment:
    - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    - FABRIC_CA_SERVER_CA_NAME=ca-org2
    - FABRIC_CA_SERVER_TLS_ENABLED=true
    - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
    - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/e725653d149a89475694801f3b8ccdafd2bf2362911773ccb7f13e1cba255327_sk
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org2.example.com-cert.pem
      --ca.keyfile /etc/hyperledger/fabric-ca-server-config/e725653d149a89475694801f3b8ccdafd2bf2362911773ccb7f13e1cba255327_sk -b admin:adminpw
      -d'
    volumes:
    - ./crypto-config/peerOrganizations/org2.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
