version: "3"
networks:
  hyperledger-ov:
    external:
      name: hyperledger-ov
services:
  couchdb0:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: couchdb0.example.com
    image: hyperledger/fabric-couchdb:latest
    networks:
      hyperledger-ov:
        aliases:
        - couchdb0
  couchdb1:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: couchdb1.example.com
    image: hyperledger/fabric-couchdb:latest
    networks:
      hyperledger-ov:
        aliases:
        - couchdb1
  couchdb2:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: couchdb2.example.com
    image: hyperledger/fabric-couchdb:latest
    networks:
      hyperledger-ov:
        aliases:
        - couchdb2
  couchdb3:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    hostname: couchdb3.example.com
    image: hyperledger/fabric-couchdb:latest
    networks:
      hyperledger-ov:
        aliases:
        - couchdb3
